export const CHANGE_SEARCH_FIELD ='CHANGE_SEARCH_FIELD';

export const REQUEST_PLAYERS_PENDING = 'REQUEST_PLAYERS_PENDING';
export const REQUEST_PLAYERS_SUCCESS = 'REQUEST_PLAYERS_SUCCESS';
export const REQUEST_PLAYERS_FAILED = 'REQUEST_PLAYERS_FAILED';